const {
  LIMIT_LENGTH_NAME,
  LIMIT_LENGTH_PHONE,
  LIMIT_LENGTH_PASSWORD,
  CONTACTS_PAGES,
  CONTACTS_LIMIT,
  FOLDER_CLOUD_AVATAR,
} = require('./constants');

const { HTTP_STATUS_CODE } = require('./constantsStatus.js');

module.exports = {
  LIMIT_LENGTH_NAME,
  LIMIT_LENGTH_PHONE,
  LIMIT_LENGTH_PASSWORD,

  CONTACTS_PAGES,
  CONTACTS_LIMIT,
  FOLDER_CLOUD_AVATAR,

  HTTP_STATUS_CODE,
};
